services:
  tracer-api:
    image: tracer-api
    container_name: tracer-api
    ports:
      - "3000:3000"
    networks:
      - tracer-network
    env_file:
      - ./server/.env.production
    build:
      context: ./server
      dockerfile: Dockerfile
    depends_on:
      tracer-db:
        condition: service_healthy

  tracer-db:
    image: postgres:14
    container_name: tracer-db
    ports:
      - "5432:5432"
    networks:
      - tracer-network
    volumes:
      - tracer-data:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=tracer
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=admin123
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d tracer"]
      interval: 5s
      timeout: 2s
      retries: 20

volumes:
  tracer-data:

networks:
 tracer-network:
  driver: bridge
  name: tracer-net