name: Server Unit Tests
run-name: running server unit tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ develop ]

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./server
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      
      - name: Install dependencies
        run: bun install
      
      - name: Run unit testing
        run: bun run test:unit